version: '3.8'
services:
  cp-minions:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - cp-rabbit
    env_file:
      - .env

  cp-rabbit:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - cp-rabbit:/var/lib/rabbitmq

  cp-redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - cp-redis:/data

    # InfluxDB - Database for sensor data
  cp-influx:
    image: influxdb:latest
    container_name: influxdb
    networks:
      - default
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    ports:
      - "8086:8086"
    volumes:
      - cp-influx:/var/lib/influxdb2
volumes:
  cp-rabbit:
  cp-redis:
  cp-influx:


