version: '3.8'
services:
  cp-minions:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - cp-rabbit
    env_file:
      - .env

  cp-rabbit:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - cp-rabbit:/var/lib/rabbitmq

  cp-redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - cp-redis:/data

  cp-vm:
    command: ["-retentionPeriod=720h"]
    image: victoriametrics/victoria-metrics
    ports:
      - "8428:8428"
    volumes:
      - cp-vm:/victoria-metrics-data

volumes:
  cp-rabbit:
  cp-redis:
  cp-vm:


