version: '3'

services:
  cp-minions:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - rabbitmq

  redis:
    image: redis:latest
    volumes:
      - ./runtime/redis/data:/data
    ports:
      - "6379:6379"

  victoriametrics:
    image: victoriametrics/victoria-metrics
    command: ["-retentionPeriod=720h"]
    volumes:
      - ./runtime/data:/victoria-metrics-data
    ports:
      - "8428:8428"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./runtime/rabbitmq/data:/var/lib/rabbitmq
